### ISSUE TITLE
Improve introduction (better cover historical context)

### ISSUE THREAD

**Issue by iimog** [molbiodiv/biojs-io-biom#28]
As a referee to our f1000 article notes:

> There is a historical context that Ankenbrand et al. miss in discussing biom-format and subsequently imply that the biom-format is more widely adopted than being field specific format. If the authors leave the introduction more general, then I would suggest they include more background on the history of high-throughput data storage and reproducibility in programmatic languages, perhaps starting with the Minimum Information About a Microarray Experiment - MIAME format [1] and exprSet classes developed in R about 15 years ago before the genomics standards consortium (formed in 2005), for which biom-format is a member.

Paulson J. Referee Report For: biojs-io-biom, a BioJS component for handling data in Biological Observation Matrix (BIOM) format [version 1; referees: 3 approved with reservations]. F1000Research 2016, 5:2348 (doi: 10.5256/f1000research.10362.r16545)

[1] Brazma A, Hingamp P, Quackenbush J, Sherlock G, Spellman P, Stoeckert C, Aach J, Ansorge W, Ball CA, Causton HC, Gaasterland T, Glenisson P, Holstege FC, Kim IF, Markowitz V, Matese JC, Parkinson H, Robinson A, Sarkans U, Schulze-Kremer S, Stewart J, Taylor R, Vilo J, Vingron M: Minimum information about a microarray experiment (MIAME)-toward standards for microarray data.Nat Genet. 2001; 29 (4): 365-71

**Comment by chiras** [comment]
you are first author :) I dont have a clue about the history as well

**Comment by iimog** [comment]
Added a little historical background as suggested by the reviewer.
