### ISSUE TITLE
Clarify second sentence

### ISSUE THREAD

**Issue by iimog** [molbiodiv/biojs-io-biom#31]
As a referee to our f1000 article notes:

> The second sentence needs clarification. “Despite this increase, for many of these studies the general basic layout of the data is similar to traditional assessment after bioinformatical processing, yet complications arise due to the increased size of the data tables.”

Paulson J. Referee Report For: biojs-io-biom, a BioJS component for handling data in Biological Observation Matrix (BIOM) format [version 1; referees: 3 approved with reservations]. F1000Research 2016, 5:2348 (doi: 10.5256/f1000research.10362.r16545)

**Comment by chiras** [comment]
the clarification comes in the following sentence... Perhaps like this:?

"Despite this increase, data formats have not changed much, yet complications arise due to the increased size of the data tables."
