### ISSUE TITLE
test different nodejs version

### ISSUE THREAD

**Issue by nterhoeven** [molbiodiv/biojs-io-biom#34]
During reproducing issue #30, I ran into problems with an old `nodejs` version. We should adapt the automated tests to different nodejs versions and probably require a recent one.

As seen below, the default nodejs version in Ubuntu 14.04 is 0.10.25. The current version 6.9.1 can be obtained via a third-party repository.
```
$ apt-cache policy nodejs
nodejs:
  Installed: 6.9.1-1nodesource1~trusty1
  Candidate: 6.9.1-1nodesource1~trusty1
  Version table:
 *** 6.9.1-1nodesource1~trusty1 0
        500 https://deb.nodesource.com/node_6.x/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.10.25~dfsg2-2ubuntu1 0
        500 http://de.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

**Comment by iimog** [comment]
Tested node versions via travis:
 - 0.1 :x:
 - 0.12 :x:
 - 4.2 :white_check_mark:
 - 4.6 :white_check_mark: 
 - 5.12 :white_check_mark: 
 - 6.9 :white_check_mark: 
 - 7.0 :white_check_mark: 

https://travis-ci.org/molbiodiv/biojs-io-biom/builds/171059935
So node version 0.x is not supported while node version >=4.2 is supported.
So we should clearly state node >=4.2 as a requirement for our module.

**Comment by iimog** [comment]
related to #30

**Comment by iimog** [comment]
Now also documented.
